version: "3"
services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo1:/data/db

  api:
    container_name: api
    ports:
      - 5001:5001
    image: api
    build: .
    command: bash -c "python run.py"
    restart: always
    # network_mode: host
    volumes:
      - .:/usr/src/app
    env_file:
      - vue.env